spring:
  application:
    name: User-Service
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
#    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: IamPawan
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  
  config:
    import: optional:configserver:http://localhost:9005


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
